set number
set ai
set si
set shiftwidth=4
set tabstop=4
set ignorecase
set cindent
set autoindent
set smartindent
set hlsearch
set expandtab
set background=dark
set fileencodings=utf-8,euc-kr
set bs=indent,eol,start
set ruler
set nobackup
set title
set nowrap
set wmnu
set hidden
syntax on

let mapleader = ","

nmap <Leader>T :enew<CR>
nmap <Leader>bq :bp <BAR> bd #<CR>
nmap <Leader>" :split<CR>
nmap <Leader>% :vsplit<CR>

map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
