LANG="ko_KR.UTF-8"
EDITOR="nvim"

ZSH_THEME="mh"
ZSH_DISABLE_COMPFIX="true"
ZSH_PLUGINS_ALIAS_TIPS_TEXT="Alias tip: "

plugins=(
    git
    autojump
    alias-tips
)

source /home/pwn/.oh-my-zsh/oh-my-zsh.sh
source /home/pwn/.linuxbrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /home/pwn/.linuxbrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

alias l="ls"
alias ll="ls -l"
alias la="ls -al"
alias vi="nvim"

alias python="python3"
alias pip="pip3"
alias ROPgadget="python3 $HOME/.ROPgadget/ROPgadget.py"
