export ZSH="$HOME/.oh-my-zsh"
export LANG="ko_KR.UTF-8"
export EDITOR="vim"

ZSH_THEME="mh"
ZSH_DISABLE_COMPFIX="true"

plugins=(
	git
)

source $ZSH/oh-my-zsh.sh

alias l="ls"
alias ll="ls -l"
alias la="ls -al"
alias vi="vim"

alias python="python3"
