export EDITOR="vim"
export LANG="C.UTF-8"
export TERM="xterm-256color"

ZSH_THEME="mh"
ZSH_DISABLE_COMPFIX="true"

plugins=(
    git
)

source /home/pwn/.oh-my-zsh/oh-my-zsh.sh

alias l="ls"
alias ll="ls -l"
alias la="ls -al"
alias vi="vim"

alias python="python3"
alias pip="pip3"
alias ROPgadget="python3 $HOME/.ROPgadget/ROPgadget.py"

set -o vi
